export const codeSnippets = [
    '#include <linux/module.h>',
    '#include <linux/kernel.h>',
    '#include <linux/init.h>',
    'static int __init hello_init(void) {',
    '    printk(KERN_INFO "Hello, Linux Kernel!\\n");',
    '    return 0;',
    '}',
    'static void __exit hello_exit(void) {',
    '    printk(KERN_INFO "Goodbye, Linux Kernel!\\n");',
    '}',
    'module_init(hello_init);',
    'module_exit(hello_exit);',
    'MODULE_LICENSE("GPL");',
    'MODULE_AUTHOR("Your Name");',
    'MODULE_DESCRIPTION("A simple Linux kernel module");',
    '// Additional Linux kernel code',
    '#include <linux/fs.h>',
    'static struct file_operations fops = {',
    '    .owner = THIS_MODULE,',
    '    .read = my_read,',
    '    .write = my_write,',
    '};',
    'static int __init my_module_init(void) {',
    '    register_chrdev(240, "my_device", &fops);',
    '    printk(KERN_INFO "My device registered\\n");',
    '    return 0;',
    '}',
    'static void __exit my_module_exit(void) {',
    '    unregister_chrdev(240, "my_device");',
    '    printk(KERN_INFO "My device unregistered\\n");',
    '}',
    'module_init(my_module_init);',
    'module_exit(my_module_exit);'
];
